[workspace]
resolver = "2"
members = [
    "nero-app",
    "nero-extensions",
    "nero-resources",
    "nero-runtime",
    "nero-types",
]

[workspace.dependencies]
anyhow = "1.0.95"
serde = { version = "1.0.219", features = ["derive"] }
tauri-plugin-shell = "2.3.0"
tokio = "1.46.1"
tracing = "0.1.41"
url = { version = "2.5.4", features = ["serde"] }
wasmtime = "34.0.1"
wasmtime-wasi = "34.0.1"
wasmtime-wasi-http = "34.0.1"
