"$schema" = "https://schema.tauri.app/config/2"
identifier = "moe.nero.app"
productName = "nero"
mainBinaryName = "nero"
version = "0.1.0"

[build]
beforeDevCommand = "bun run dev"
beforeBuildCommand = "bun run build"
frontendDist = "../nero-ui/dist"
devUrl = "http://localhost:1420"

[bundle]
active = true
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[[app.windows]]
title = "Nero"
width = 1024
height = 640
minWidth = 768
minHeight = 480
maxWidth = 1280
maxHeight = 800
